
media:
  - name: chats
    label: Photos des chats
    input: images/chats
    output: /images/chats
    categories: [image]

  - name: sauvetages
    label: Photos des sauvetages
    input: images/sauvetages
    output: /images/sauvetages
    categories: [image]

content:
  # NOS SAUVETAGES
  - name: sauvetages
    label: Nos sauvetages
    type: collection
    path: _sauvetages
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Titre du sauvetage
        type: string
        required: true

      - name: date
        label: Date du sauvetage
        type: date
        required: true

      - name: image
        label: Photo du chat
        type: image
        required: true

      - name: body
        label: Histoire du sauvetage
        type: rich-text
        required: true

  # TOUS LES CHATS : ADOPTION ET FAMILLES
  - name: chats
    label: Tous les chats
    type: collection
    path: _chats
    filename: "{primary}.md"
    fields:
      - name: title
        label: Nom du chat
        type: string
        required: true

      - name: date
        label: Date de publication
        type: date
        required: true

      - name: date_adoption
        label: Date d'adoption
        type: date

      - name: image
        label: Photo du chat
        type: image
        required: true

      - name: statut
        label: Statut du chat
        type: select
        options:
          values:
            - À l'adoption
            - Adopté
        required: true

      - name: age
        label: Âge du chat
        type: string

      - name: sexe
        label: Sexe du chat
        type: select
        options:
          values:
            - Femelle
            - Mâle
            - Inconnu

      - name: caractere
        label: Caractère et description
        type: rich-text

      - name: conditions
        label: Conditions d'adoption
        type: rich-text

      - name: histoire
        label: Son histoire
        type: rich-text

      - name: body
        label: Informations complémentaires
        type: rich-text
